jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install renv and restore packages
        run: |
          Rscript -e 'install.packages("renv", repos="https://cran.r-project.org")'
          Rscript -e 'renv::restore(prompt = FALSE)'

      - uses: quarto-dev/quarto-actions/setup@v2

      - run: quarto render

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
